export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';
export const CHANGE_MODE = 'CHANGE_THEME_MODE';
export const UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION';
export const UPDATE_NEW_CHAT_ALERT = 'UPDATE_NEW_CHAT_ALERT';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const ATTACH_SOCKET = 'ATTACH_SOCKET';